### Get all todos
GET http://localhost:3000/todos

### Get one todos
GET http://localhost:3000/todos/1779598166660

### Create todo (valid request)
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Learn NestJS",
  "completed": false
}

### Delete one todo
DELETE http://localhost:3000/todos/1779598561043

### Create todo (invalid - should fail validation)
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": 123,
  "completed": "no"
}

### Create todo (missing field test)
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Missing completed"
}

### Update both title and completed
PATCH http://localhost:3000/todos/1779598561135
Content-Type: application/json

{
  "title": "Updated todo title",
  "completed": true
}

### Update only title
PATCH http://localhost:3000/todos/1779598339542
Content-Type: application/json

{
  "title": "Updated title only"
}

### Update only completed
PATCH http://localhost:3000/todos/1779598561135
Content-Type: application/json

{
  "completed": false
}